sudo: required
language: node_js
node_js:
  - "8"
matrix:
  include:
  - os: osx

before_install:
  - npm install
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

script:
  - PATH=$(npm bin):$PATH
  - electron-packager . --overwrite --platform=darwin --arch=x64 --icon=./images/goatIcon.icns --prune=true --out=release-builds
  - cp -r ./release-builds/*/*.app ./
  - git checkout master
  - git add ./*.app
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin-pages https://github.com/jrrombaldo/cabrito.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-pages gh-pages 

