sudo: required
language: node_js
node_js:
  - "8"
matrix:
  include:
  - os: osx

before_install:
  - npm install

script:
  - PATH=$(npm bin):$PATH
  - electron-packager . --overwrite --platform=darwin --arch=x64 --icon=./images/goatIcon.icns --prune=true --out=release-builds